export const subjectNames = {
    matte: 'Matematik',
    svenska: 'Svenska',
    engelska: 'Engelska',
    no: 'NO',
    so: 'Geografi',
    historia: 'Historia',
};

export const questions = {
    matte: [
        { q: 'Vad är 7 × 8?', answers: ['54', '56', '64', '48'], correct: 1 },
        { q: 'Kvadratroten ur 144?', answers: ['11', '12', '13', '14'], correct: 1 },
        { q: 'Vad är 15% av 200?', answers: ['25', '30', '35', '20'], correct: 1 },
        { q: 'Hur många sidor har en hexagon?', answers: ['5', '7', '6', '8'], correct: 2 },
        { q: 'Vad är 2³ + 3²?', answers: ['15', '17', '19', '13'], correct: 1 },
        { q: 'Vilket tal är ett primtal?', answers: ['9', '15', '17', '21'], correct: 2 },
        { q: 'Vad är 1/4 + 1/2?', answers: ['2/6', '3/4', '2/4', '1/3'], correct: 1 },
        { q: 'Omkrets av kvadrat med sidan 5?', answers: ['10', '15', '20', '25'], correct: 2 },
        { q: 'Vad är 3/5 av 100?', answers: ['30', '50', '60', '45'], correct: 2 },
        { q: 'Nästa primtal efter 13?', answers: ['14', '15', '16', '17'], correct: 3 },
    ],
    svenska: [
        { q: 'Vilket ord är ett substantiv?', answers: ['Spring', 'Snabb', 'Hund', 'Röd'], correct: 2 },
        { q: "Synonym till 'glad'?", answers: ['Ledsen', 'Trött', 'Lycklig', 'Arg'], correct: 2 },
        { q: 'Vilket är ett adjektiv?', answers: ['Hoppa', 'Bord', 'Vacker', 'Snabbt'], correct: 2 },
        { q: 'Vad heter satsens kärna?', answers: ['Subjekt', 'Predikat', 'Objekt', 'Adverbial'], correct: 1 },
        { q: 'Vilket ord stavas rätt?', answers: ['Examen', 'Exxamen', 'Eksamen', 'Egzamen'], correct: 0 },
        { q: "Antonym till 'stor'?", answers: ['Bred', 'Lång', 'Liten', 'Hög'], correct: 2 },
        { q: 'Vilket är ett verb?', answers: ['Röd', 'Snabbt', 'Springer', 'Hund'], correct: 2 },
        { q: 'Vad är en metafor?', answers: ['En rimrad dikt', 'En bildlig jämförelse', 'Ett nyord', 'En mening'], correct: 1 },
    ],
    engelska: [
        { q: "What is 'äpple' in English?", answers: ['Orange', 'Apple', 'Pear', 'Banana'], correct: 1 },
        { q: "What does 'beautiful' mean?", answers: ['Ful', 'Konstig', 'Vacker', 'Stor'], correct: 2 },
        { q: "Past tense of 'go'?", answers: ['Goed', 'Gone', 'Went', 'Goes'], correct: 2 },
        { q: "What is 'hund' in English?", answers: ['Cat', 'Dog', 'Bird', 'Horse'], correct: 1 },
        { q: "Which word means 'snabb'?", answers: ['Slow', 'Fast', 'Heavy', 'Tall'], correct: 1 },
        { q: "What does 'library' mean?", answers: ['Bokhandel', 'Skola', 'Bibliotek', 'Museum'], correct: 2 },
        { q: "How do you say 'tack'?", answers: ['Please', 'Sorry', 'Hello', 'Thank you'], correct: 3 },
        { q: "Plural of 'child'?", answers: ['Childs', 'Childes', 'Children', 'Childrens'], correct: 2 },
    ],
    no: [
        { q: 'Grundämne med symbolen O?', answers: ['Guld', 'Ozon', 'Syre', 'Osmium'], correct: 2 },
        { q: 'Hur många ben har ett insekt?', answers: ['4', '6', '8', '10'], correct: 1 },
        { q: 'Jordens innersta lager?', answers: ['Manteln', 'Skorpan', 'Inre kärnan', 'Yttre kärnan'], correct: 2 },
        { q: 'Vilket organ pumpar blodet?', answers: ['Lungan', 'Hjärnan', 'Njuren', 'Hjärtat'], correct: 3 },
        { q: 'Vad producerar fotosyntesen?', answers: ['CO₂', 'Vatten', 'Socker och O₂', 'Kväve'], correct: 2 },
        { q: 'Minsta delen av ett grundämne?', answers: ['Molekyl', 'Atom', 'Neutron', 'Elektron'], correct: 1 },
        { q: 'Vilken planet är närmast solen?', answers: ['Venus', 'Mars', 'Merkurius', 'Jorden'], correct: 2 },
        { q: 'Vad är DNA?', answers: ['Ett protein', 'Ärftlig information', 'En cell', 'Ett virus'], correct: 1 },
    ],
    so: [
        { q: 'Vilket land har flest invånare?', answers: ['Indien', 'USA', 'Ryssland', 'Kina'], correct: 3 },
        { q: 'Vad heter Sveriges riksdag?', answers: ['Stortinget', 'Riksdagen', 'Folketinget', 'Altinget'], correct: 1 },
        { q: 'Vilket hav är störst?', answers: ['Atlanten', 'Indiska oceanen', 'Arktiska oceanen', 'Stilla havet'], correct: 3 },
        { q: 'Hur många kommuner i Sverige?', answers: ['190', '290', '390', '490'], correct: 1 },
        { q: 'Vad kallas folk som flyr till annat land?', answers: ['Turister', 'Flyktingar', 'Invandrare', 'Diplomater'], correct: 1 },
        { q: 'Vilket land är störst till ytan?', answers: ['Kanada', 'Kina', 'USA', 'Ryssland'], correct: 3 },
    ],
    historia: [
        { q: 'När började första världskriget?', answers: ['1904', '1914', '1918', '1939'], correct: 1 },
        { q: 'Vilket år föll Berlinmuren?', answers: ['1985', '1987', '1989', '1991'], correct: 2 },
        { q: 'Atenska demokratins grundare?', answers: ['Sokrates', 'Perikles', 'Solon', 'Platon'], correct: 2 },
        { q: 'När avskaffades slaveriet i USA?', answers: ['1848', '1863', '1876', '1901'], correct: 1 },
        { q: 'Apollo 11 landade på månen?', answers: ['1965', '1967', '1969', '1971'], correct: 2 },
        { q: 'Frankrikes kejsare på 1800-talet?', answers: ['Ludvig XIV', 'Robespierre', 'Napoleon', 'Richelieu'], correct: 2 },
        { q: 'Andra världskriget startade?', answers: ['1935', '1937', '1939', '1941'], correct: 2 },
        { q: 'Vad var Kolosseum?', answers: ['Ett tempel', 'En amfiteater', 'Ett palats', 'En marknadsplats'], correct: 1 },
    ],
};