export const subjectNames = {
    matte: "Matematik",
    svenska: "Svenska",
    engelska: "Engelska",
    no: "NO",
    so: "Geografi",
    historia: "Historia",
};

export const gradeNames = {
    1: "Årskurs 1",
    2: "Årskurs 2",
    3: "Årskurs 3",
    4: "Årskurs 4",
    5: "Årskurs 5",
    6: "Årskurs 6",
    7: "Årskurs 7",
    8: "Årskurs 8",
    9: "Årskurs 9",
};

const lowerGradeQuestions = {
    matte: [
        { q: "Vad är 4 + 3?", answers: ["6", "7", "8", "9"], correct: 1 },
        { q: "Vad är 10 - 4?", answers: ["5", "6", "7", "8"], correct: 1 },
        { q: "Vilket tal kommer efter 19?", answers: ["18", "20", "21", "29"], correct: 1 },
        { q: "Hur många hörn har en triangel?", answers: ["2", "3", "4", "5"], correct: 1 },
        { q: "Vad är hälften av 8?", answers: ["2", "3", "4", "6"], correct: 2 },
        { q: "Vad är 2 + 2 + 2?", answers: ["4", "5", "6", "8"], correct: 2 },
        { q: "Vilket tal är störst?", answers: ["12", "9", "15", "7"], correct: 2 },
        { q: "Hur många tiotal finns i 30?", answers: ["2", "3", "4", "30"], correct: 1 },
        { q: "Vad är 5 + 5?", answers: ["8", "9", "10", "11"], correct: 2 },
        { q: "Vad är 12 - 2?", answers: ["8", "9", "10", "12"], correct: 2 },
        { q: "Vilket tal är minst?", answers: ["6", "3", "9", "5"], correct: 1 },
        { q: "Hur många sidor har en fyrkant?", answers: ["3", "4", "5", "6"], correct: 1 },
        { q: "Vad är dubbelt så mycket som 4?", answers: ["6", "7", "8", "9"], correct: 2 },
        { q: "Vad är 20 + 1?", answers: ["19", "20", "21", "22"], correct: 2 },
        { q: "Vad är 3 + 6?", answers: ["8", "9", "10", "11"], correct: 1 },
        { q: "Vilket tal kommer före 15?", answers: ["13", "14", "16", "17"], correct: 1 },
    ],
    svenska: [
        { q: "Vilken bokstav börjar ordet \"sol\" med?", answers: ["S", "L", "O", "T"], correct: 0 },
        { q: "Vilket ord rimmar på \"katt\"?", answers: ["Hund", "Hatt", "Sol", "Bok"], correct: 1 },
        { q: "Vilket ord är ett djur?", answers: ["Stol", "Kanin", "Sked", "Hus"], correct: 1 },
        { q: "Vilket ord är en färg?", answers: ["Springa", "Blå", "Bord", "Sova"], correct: 1 },
        { q: "Vad sätter vi i slutet av en fråga?", answers: ["Punkt", "Komma", "Frågetecken", "Bindestreck"], correct: 2 },
        { q: "Vilket ord är motsatsen till \"glad\"?", answers: ["Ledsen", "Snäll", "Varm", "Lång"], correct: 0 },
        { q: "Vilket ord är längst?", answers: ["Bil", "Blomma", "Ko", "Sol"], correct: 1 },
        { q: "Vilket ord börjar med samma ljud som \"måne\"?", answers: ["Mat", "Sol", "Bok", "Fisk"], correct: 0 },
        { q: "Vilket ord börjar med B?", answers: ["Sol", "Boll", "Katt", "Fisk"], correct: 1 },
        { q: "Vilket ord är en sak?", answers: ["Bord", "Hoppa", "Glad", "Fort"], correct: 0 },
        { q: "Vilket ord rimmar på \"bil\"?", answers: ["Pil", "Bok", "Hus", "Sol"], correct: 0 },
        { q: "Vilket ord är motsatsen till \"kall\"?", answers: ["Varm", "Blå", "Stor", "Tyst"], correct: 0 },
        { q: "Vilket ord är ett namn?", answers: ["Anna", "Springa", "Gul", "Bord"], correct: 0 },
        { q: "Vilket ord har tre bokstäver?", answers: ["Blomma", "Sol", "Kanin", "Skola"], correct: 1 },
        { q: "Vilket ord är motsatsen till \"upp\"?", answers: ["Ner", "Bred", "Mjuk", "Rund"], correct: 0 },
        { q: "Vilket ord är något man kan läsa?", answers: ["Bok", "Sten", "Moln", "Sked"], correct: 0 },
    ],
    engelska: [
        { q: "What is 'katt' in English?", answers: ["Dog", "Cat", "Fish", "Bird"], correct: 1 },
        { q: "What is 'röd' in English?", answers: ["Blue", "Red", "Green", "Yellow"], correct: 1 },
        { q: "What does 'hello' mean?", answers: ["Hej", "Tack", "Hej då", "Snälla"], correct: 0 },
        { q: "What is 'bok' in English?", answers: ["Book", "Ball", "Bag", "Box"], correct: 0 },
        { q: "Which word means 'sol'?", answers: ["Moon", "Sun", "Star", "Cloud"], correct: 1 },
        { q: "What is 'en' in English?", answers: ["One", "Two", "Three", "Four"], correct: 0 },
        { q: "What is 'blå' in English?", answers: ["Black", "Blue", "Brown", "White"], correct: 1 },
        { q: "What does 'goodbye' mean?", answers: ["God morgon", "Hej då", "Förlåt", "Tack"], correct: 1 },
        { q: "What is 'hund' in English?", answers: ["Cat", "Dog", "Bird", "Fish"], correct: 1 },
        { q: "What is 'gul' in English?", answers: ["Yellow", "Blue", "Red", "Green"], correct: 0 },
        { q: "What does 'yes' mean?", answers: ["Nej", "Ja", "Hej", "Tack"], correct: 1 },
        { q: "What is 'hus' in English?", answers: ["House", "Horse", "Mouse", "Hat"], correct: 0 },
        { q: "Which word means 'måne'?", answers: ["Sun", "Moon", "Star", "Tree"], correct: 1 },
        { q: "What is 'två' in English?", answers: ["One", "Two", "Three", "Ten"], correct: 1 },
        { q: "What is 'grön' in English?", answers: ["Green", "Grey", "Blue", "Brown"], correct: 0 },
        { q: "What does 'no' mean?", answers: ["Ja", "Nej", "Hej", "Bra"], correct: 1 },
    ],
    no: [
        { q: "Vad behöver växter för att växa?", answers: ["Godis", "Vatten", "Plast", "Sandpapper"], correct: 1 },
        { q: "Vilket djur kan flyga?", answers: ["Fågel", "Häst", "Ko", "Mask"], correct: 0 },
        { q: "Vilken kroppsdel använder vi för att se?", answers: ["Ögon", "Fötter", "Knän", "Armbågar"], correct: 0 },
        { q: "Vad kallas fruset vatten?", answers: ["Ånga", "Is", "Sand", "Lera"], correct: 1 },
        { q: "Vilken årstid är oftast kallast?", answers: ["Sommar", "Vinter", "Vår", "Höst"], correct: 1 },
        { q: "Vad andas människor in?", answers: ["Syre", "Sten", "Ljus", "Jord"], correct: 0 },
        { q: "Vilket djur lever ofta i vatten?", answers: ["Fisk", "Kanin", "Höna", "Får"], correct: 0 },
        { q: "Vad ger solen oss?", answers: ["Ljus och värme", "Bara ljud", "Bara regn", "Snö"], correct: 0 },
        { q: "Vad har människor på huvudet?", answers: ["Hår", "Rötter", "Fenor", "Vingar"], correct: 0 },
        { q: "Vilket djur säger ofta mjau?", answers: ["Katt", "Hund", "Ko", "Häst"], correct: 0 },
        { q: "Vad faller från moln när det regnar?", answers: ["Vatten", "Stenar", "Löv", "Sand"], correct: 0 },
        { q: "Vad växer på träd?", answers: ["Löv", "Skor", "Böcker", "Lampor"], correct: 0 },
        { q: "Vilket sinne använder vi för att höra?", answers: ["Hörsel", "Syn", "Smak", "Lukt"], correct: 0 },
        { q: "Vad behöver vi för att andas?", answers: ["Luft", "Papper", "Metall", "Lera"], correct: 0 },
        { q: "Vad använder vi näsan till?", answers: ["Lukta", "Höra", "Gå", "Skriva"], correct: 0 },
        { q: "Vad kallas en ung hund?", answers: ["Valp", "Kalv", "Föl", "Kyckling"], correct: 0 },
    ],
    so: [
        { q: "Vad heter landet vi bor i?", answers: ["Norge", "Sverige", "Finland", "Danmark"], correct: 1 },
        { q: "Vad heter Sveriges huvudstad?", answers: ["Malmö", "Göteborg", "Stockholm", "Uppsala"], correct: 2 },
        { q: "Vad visar en karta?", answers: ["Musik", "Platser", "Sagor", "Maträtter"], correct: 1 },
        { q: "Vilken färg har Sveriges flagga?", answers: ["Röd och vit", "Blå och gul", "Grön och vit", "Svart och gul"], correct: 1 },
        { q: "Vad kallas en person som bor nära dig?", answers: ["Granne", "Kapten", "Lärare", "Kock"], correct: 0 },
        { q: "Vilket håll går solen oftast upp?", answers: ["Öster", "Väster", "Norr", "Söder"], correct: 0 },
        { q: "Vad är en stad?", answers: ["En plats där människor bor", "Ett djur", "En växt", "En bokstav"], correct: 0 },
        { q: "Vad använder vi pengar till?", answers: ["Att köpa saker", "Att måla himlen", "Att laga moln", "Att sova"], correct: 0 },
        { q: "Vad heter människorna i en familj ofta?", answers: ["Familjemedlemmar", "Kartor", "Hus", "Berg"], correct: 0 },
        { q: "Vad är en skola?", answers: ["En plats där man lär sig", "Ett hav", "En färg", "Ett djur"], correct: 0 },
        { q: "Vad kan en flagga visa?", answers: ["Ett land", "En smak", "En siffra", "Ett ljud"], correct: 0 },
        { q: "Vad heter platsen där man lånar böcker?", answers: ["Bibliotek", "Strand", "Kök", "Garage"], correct: 0 },
        { q: "Vad är en väg?", answers: ["Där man kan färdas", "En maträtt", "En färg", "Ett väder"], correct: 0 },
        { q: "Vad betyder regler?", answers: ["Sådant vi kommer överens om", "Bara leksaker", "Bara moln", "Bara siffror"], correct: 0 },
        { q: "Vad gör en brandstation?", answers: ["Hjälper vid bränder", "Säljer böcker", "Odlar mat", "Målar vägar"], correct: 0 },
        { q: "Vad är en adress?", answers: ["Var någon bor", "En maträtt", "En årstid", "Ett djur"], correct: 0 },
    ],
    historia: [
        { q: "Vad betyder \"förr i tiden\"?", answers: ["Framtiden", "Det som hänt tidigare", "En plats", "En färg"], correct: 1 },
        { q: "Vad kan berätta om gamla tider?", answers: ["Fotografier", "Bara skor", "Bara moln", "Bara ljud"], correct: 0 },
        { q: "Vad kom först?", answers: ["Datorn", "Mobilen", "Hjulet", "Surfplattan"], correct: 2 },
        { q: "Vad är ett museum?", answers: ["En plats med gamla saker och kunskap", "En fotbollsplan", "En skog", "En buss"], correct: 0 },
        { q: "Vad kallas berättelser från förr?", answers: ["Historia", "Matte", "Idrott", "Musik"], correct: 0 },
        { q: "Vad användes brev till förr?", answers: ["Skicka meddelanden", "Bygga hus", "Mäta regn", "Göra eld"], correct: 0 },
        { q: "Vad är en tidslinje?", answers: ["Saker i tidsordning", "En karta över hav", "En sång", "En boll"], correct: 0 },
        { q: "Vad kan en gammal byggnad visa?", answers: ["Hur människor byggde förr", "Vad alla åt idag", "Framtidens väder", "En hemlig färg"], correct: 0 },
        { q: "Vad är något gammalt?", answers: ["En sak från förr", "En sak från imorgon", "En ny idé", "En framtida plats"], correct: 0 },
        { q: "Vad kan en mormor berätta om?", answers: ["Saker hon varit med om", "Bara kartor", "Bara siffror", "Bara färger"], correct: 0 },
        { q: "Vad kom före idag?", answers: ["Igår", "Imorgon", "Nästa vecka", "Framtiden"], correct: 0 },
        { q: "Vad är en gammal leksak ett exempel på?", answers: ["Spår från förr", "En väderlek", "En planet", "En årstid"], correct: 0 },
        { q: "Vad betyder \"nu\"?", answers: ["Den här tiden", "För länge sedan", "Nästa år", "En plats"], correct: 0 },
        { q: "Vad kan en bild från förr visa?", answers: ["Hur det såg ut då", "Framtidens mat", "Vädret om tio år", "En hemlig siffra"], correct: 0 },
        { q: "Vad kommer efter idag?", answers: ["Imorgon", "Igår", "Förra året", "Förr"], correct: 0 },
        { q: "Vad är ett minne?", answers: ["Något man kommer ihåg", "En sorts sten", "En karta", "En färg"], correct: 0 },
    ],
};

const middleGradeQuestions = {
    matte: [
        { q: "Vad är 6 × 7?", answers: ["36", "40", "42", "48"], correct: 2 },
        { q: "Vad är 120 / 4?", answers: ["20", "25", "30", "40"], correct: 2 },
        { q: "Vad är 3/4 av 20?", answers: ["10", "12", "15", "18"], correct: 2 },
        { q: "Hur många grader är en rät vinkel?", answers: ["45", "90", "120", "180"], correct: 1 },
        { q: "Vad är 0,5 som bråk?", answers: ["1/4", "1/3", "1/2", "2/3"], correct: 2 },
        { q: "Vad är arean av en rektangel 4 × 5?", answers: ["9", "18", "20", "25"], correct: 2 },
        { q: "Vad är 10% av 80?", answers: ["4", "8", "10", "18"], correct: 1 },
        { q: "Vilket tal är delbart med 3?", answers: ["14", "22", "27", "35"], correct: 2 },
        { q: "Vad är 9 × 8?", answers: ["64", "72", "81", "88"], correct: 1 },
        { q: "Vad är 250 + 150?", answers: ["300", "350", "400", "450"], correct: 2 },
        { q: "Vad är 1/2 av 36?", answers: ["12", "16", "18", "20"], correct: 2 },
        { q: "Vad är 7²?", answers: ["14", "42", "49", "56"], correct: 2 },
        { q: "Hur många minuter är 2 timmar?", answers: ["60", "90", "120", "140"], correct: 2 },
        { q: "Vad är 15% av 100?", answers: ["10", "15", "20", "25"], correct: 1 },
        { q: "Vad är 360 / 6?", answers: ["40", "50", "60", "70"], correct: 2 },
        { q: "Vad är 2,5 + 1,5?", answers: ["3", "4", "4,5", "5"], correct: 1 },
    ],
    svenska: [
        { q: "Vilket ord är ett verb?", answers: ["Bord", "Springer", "Röd", "Snabbt"], correct: 1 },
        { q: "Vad är en synonym?", answers: ["Ett ord med motsatt betydelse", "Ett ord med liknande betydelse", "Ett skiljetecken", "En rubrik"], correct: 1 },
        { q: "Vilket ord är ett adjektiv?", answers: ["Vacker", "Hoppa", "Stol", "Imorgon"], correct: 0 },
        { q: "Vad börjar en mening med?", answers: ["Liten bokstav", "Stor bokstav", "Komma", "Bindestreck"], correct: 1 },
        { q: "Vilket är ett substantiv?", answers: ["Hund", "Springa", "Glad", "Fort"], correct: 0 },
        { q: "Vad är motsatsen till \"mörk\"?", answers: ["Svart", "Ljus", "Lång", "Tyst"], correct: 1 },
        { q: "Vad används en rubrik till?", answers: ["Visa vad texten handlar om", "Räkna ord", "Gömma text", "Byta språk"], correct: 0 },
        { q: "Vilket skiljetecken avslutar ofta ett påstående?", answers: ["Frågetecken", "Punkt", "Kolon", "Citationstecken"], correct: 1 },
        { q: "Vad är en antonym?", answers: ["Ett motsatsord", "Ett rim", "Ett frågetecken", "En titel"], correct: 0 },
        { q: "Vilket ord är ett pronomen?", answers: ["Hon", "Bord", "Springa", "Blå"], correct: 0 },
        { q: "Vad kallas textens början ofta?", answers: ["Inledning", "Tabell", "Fotnot", "Register"], correct: 0 },
        { q: "Vilket ord är rättstavat?", answers: ["Sjukhus", "Skukhus", "Sjukus", "Shukhus"], correct: 0 },
        { q: "Vad är en huvudperson?", answers: ["En viktig person i en berättelse", "En rubrik", "Ett skiljetecken", "En plats på kartan"], correct: 0 },
        { q: "Vilket ord är ett adverb?", answers: ["Snabbt", "Snabb", "Hund", "Springer"], correct: 0 },
        { q: "Vad är dialog?", answers: ["När personer pratar med varandra", "En faktaruta", "En karta", "En stavelse"], correct: 0 },
        { q: "Vad är en miljöbeskrivning?", answers: ["Beskrivning av platsen", "En lista med verb", "En sorts rim", "En rubrik"], correct: 0 },
    ],
    engelska: [
        { q: "What is 'skola' in English?", answers: ["School", "Street", "Shop", "Sky"], correct: 0 },
        { q: "What is the plural of 'dog'?", answers: ["Doges", "Dogs", "Dogies", "Dog"], correct: 1 },
        { q: "What does 'hungry' mean?", answers: ["Trött", "Hungrig", "Arg", "Snabb"], correct: 1 },
        { q: "Past tense of 'play'?", answers: ["Played", "Plaied", "Playd", "Playing"], correct: 0 },
        { q: "Which word means 'vän'?", answers: ["Enemy", "Friend", "Family", "Teacher"], correct: 1 },
        { q: "What is 'morgon' in English?", answers: ["Evening", "Morning", "Night", "Noon"], correct: 1 },
        { q: "What does 'read' mean?", answers: ["Läsa", "Springa", "Skriva", "Titta"], correct: 0 },
        { q: "Which sentence is correct?", answers: ["I am happy", "I is happy", "I are happy", "I be happy"], correct: 0 },
        { q: "What does 'small' mean?", answers: ["Liten", "Stor", "Snabb", "Varm"], correct: 0 },
        { q: "Past tense of 'jump'?", answers: ["Jumped", "Jumpt", "Jumpen", "Jumps"], correct: 0 },
        { q: "What is 'lärare' in English?", answers: ["Teacher", "Student", "Doctor", "Driver"], correct: 0 },
        { q: "Which word means 'familj'?", answers: ["Family", "Friend", "Food", "Forest"], correct: 0 },
        { q: "What does 'write' mean?", answers: ["Skriva", "Läsa", "Lyssna", "Räkna"], correct: 0 },
        { q: "Which is correct?", answers: ["She has a book", "She have a book", "She having a book", "She haves a book"], correct: 0 },
        { q: "What is 'väder' in English?", answers: ["Weather", "Water", "Winter", "Window"], correct: 0 },
        { q: "What does 'because' mean?", answers: ["Eftersom", "Men", "Aldrig", "Snart"], correct: 0 },
    ],
    no: [
        { q: "Vilken planet bor vi på?", answers: ["Mars", "Venus", "Jorden", "Jupiter"], correct: 2 },
        { q: "Vad kallas vatten i gasform?", answers: ["Is", "Ånga", "Snö", "Hagel"], correct: 1 },
        { q: "Vilket organ pumpar blod?", answers: ["Hjärtat", "Lungan", "Magen", "Levern"], correct: 0 },
        { q: "Vad gör bin när de besöker blommor?", answers: ["Pollinerar", "Fryser vatten", "Bygger stenar", "Släcker ljus"], correct: 0 },
        { q: "Vilket ämne andas växter in för fotosyntes?", answers: ["Koldioxid", "Guld", "Salt", "Helium"], correct: 0 },
        { q: "Vad kallas djur utan ryggrad?", answers: ["Ryggradslösa djur", "Däggdjur", "Fåglar", "Reptiler"], correct: 0 },
        { q: "Vilken kraft drar saker mot marken?", answers: ["Gravitation", "Magnetism", "Friktion", "Elektricitet"], correct: 0 },
        { q: "Vad behöver kroppen för att bygga starka ben?", answers: ["Kalcium", "Plast", "Olja", "Sand"], correct: 0 },
        { q: "Vad kallas djur som ger sina ungar mjölk?", answers: ["Däggdjur", "Fiskar", "Insekter", "Växter"], correct: 0 },
        { q: "Vad gör lungorna?", answers: ["Hjälper oss att andas", "Tuggar mat", "Pumpar blod", "Ser färger"], correct: 0 },
        { q: "Vad är en näringskedja?", answers: ["Vem som äter vem", "En karta", "En sten", "En väderprognos"], correct: 0 },
        { q: "Vilket material dras ofta till en magnet?", answers: ["Järn", "Trä", "Glas", "Papper"], correct: 0 },
        { q: "Vad kallas vattnets väg runt i naturen?", answers: ["Kretslopp", "Erosion", "Friktion", "Fotosyntes"], correct: 0 },
        { q: "Vad skyddar huden mot?", answers: ["Skador och smuts", "Matteproblem", "Kartor", "Ljud"], correct: 0 },
        { q: "Vad behöver växter mer än vatten och ljus?", answers: ["Koldioxid", "Plast", "Bensin", "Järnspik"], correct: 0 },
        { q: "Vad kallas ämnen som inte leder ström bra?", answers: ["Isolatorer", "Ledare", "Magneter", "Kretsar"], correct: 0 },
    ],
    so: [
        { q: "Vad är en kommun?", answers: ["Ett lokalt område som styr vissa frågor", "Ett berg", "En valuta", "Ett hav"], correct: 0 },
        { q: "Vilket väderstreck ligger norr mitt emot?", answers: ["Söder", "Öster", "Väster", "Nordost"], correct: 0 },
        { q: "Vad är demokrati?", answers: ["Att människor får vara med och bestämma", "Att en person bestämmer allt", "En flod", "En skatt"], correct: 0 },
        { q: "Vad visar höjdkurvor på en karta?", answers: ["Höjdskillnader", "Språk", "Valuta", "Befolkningens ålder"], correct: 0 },
        { q: "Vilket hav ligger öster om Sverige?", answers: ["Östersjön", "Atlanten", "Medelhavet", "Nordsjön"], correct: 0 },
        { q: "Vad är export?", answers: ["Varor som säljs till andra länder", "Varor som slängs", "En typ av berg", "Ett väderstreck"], correct: 0 },
        { q: "Vilket landskap ligger Stockholm i?", answers: ["Skåne", "Uppland", "Dalarna", "Lappland"], correct: 1 },
        { q: "Vad visar en politisk karta?", answers: ["Länder och gränser", "Bara väder", "Bara djur", "Bara bergarter"], correct: 0 },
        { q: "Vad är import?", answers: ["Varor som köps från andra länder", "En sjö", "En stad", "Ett väderstreck"], correct: 0 },
        { q: "Vad heter Sveriges statschef?", answers: ["Kungen", "Rektorn", "Borgmästaren", "Domaren"], correct: 0 },
        { q: "Vad betyder befolkning?", answers: ["Människor som bor på en plats", "Bara hus", "Bara vägar", "Bara pengar"], correct: 0 },
        { q: "Vilket land gränsar till Sverige i väster?", answers: ["Norge", "Polen", "Island", "Spanien"], correct: 0 },
        { q: "Vad är en budget?", answers: ["Plan för pengar", "En karta", "En lagbok", "Ett landskap"], correct: 0 },
        { q: "Vad kallas ett val där folket röstar?", answers: ["Demokratiskt val", "Väderval", "Kartval", "Språkval"], correct: 0 },
        { q: "Vad är skatt?", answers: ["Pengar till gemensamma saker", "Ett hav", "En bergart", "En vind"], correct: 0 },
        { q: "Vad kallas en karta över höjd och natur?", answers: ["Topografisk karta", "Sagokarta", "Musikkarta", "Matkarta"], correct: 0 },
    ],
    historia: [
        { q: "Vad kallas tiden då människor ofta bodde i grottor och jagade?", answers: ["Stenåldern", "Medeltiden", "Nutiden", "Industrialiseringen"], correct: 0 },
        { q: "Vad var vikingar kända för?", answers: ["Resor och handel", "Rymdraketer", "Bilar", "Datorer"], correct: 0 },
        { q: "Vad är en källa i historia?", answers: ["Något som berättar om det förflutna", "En sjö", "En miniräknare", "Ett instrument"], correct: 0 },
        { q: "Vilken stad var viktig för vikingahandel i Sverige?", answers: ["Birka", "Kiruna", "Visby", "Lund"], correct: 0 },
        { q: "Vad kallas tiden mellan vikingatid och vasatid?", answers: ["Medeltiden", "Bronsåldern", "Nutiden", "Framtiden"], correct: 0 },
        { q: "Vem var Gustav Vasa?", answers: ["En svensk kung", "En romersk kejsare", "En uppfinnare av telefonen", "En astronaut"], correct: 0 },
        { q: "Vad betyder arkeologi?", answers: ["Att undersöka spår från förr", "Att räkna pengar", "Att odla växter", "Att skriva musik"], correct: 0 },
        { q: "Vad var en runsten?", answers: ["En sten med runskrift", "En bro av trä", "Ett vapen", "En karta"], correct: 0 },
        { q: "Vad var digerdöden?", answers: ["En svår sjukdom", "Ett skepp", "En kung", "En karta"], correct: 0 },
        { q: "Vad är en tidsperiod?", answers: ["En del av historien", "Ett djur", "En färg", "En flod"], correct: 0 },
        { q: "Vilket material användes mycket under bronsåldern?", answers: ["Brons", "Plast", "Aluminium", "Glasfiber"], correct: 0 },
        { q: "Vad gjorde munkar ofta på medeltiden?", answers: ["Skrev och kopierade texter", "Körde bilar", "Byggde datorer", "Flög flygplan"], correct: 0 },
        { q: "Vad betyder handel?", answers: ["Att köpa och sälja", "Att sova", "Att måla", "Att simma"], correct: 0 },
        { q: "Vad är en historisk händelse?", answers: ["Något viktigt som hänt", "En framtidsplan", "En siffra", "En väderlek"], correct: 0 },
        { q: "Vad var reformationen?", answers: ["En förändring inom kyrkan", "En järnväg", "En vikingabåt", "En sorts skatt"], correct: 0 },
        { q: "Vad betyder kronologi?", answers: ["Tidsordning", "Rimordning", "Kartläsning", "Måttordning"], correct: 0 },
    ],
};

const upperGradeQuestions = {
    matte: [
        { q: "Vad är 7 × 8?", answers: ["54", "56", "64", "48"], correct: 1 },
        { q: "Kvadratroten ur 144?", answers: ["11", "12", "13", "14"], correct: 1 },
        { q: "Vad är 15% av 200?", answers: ["25", "30", "35", "20"], correct: 1 },
        { q: "Hur många sidor har en hexagon?", answers: ["5", "7", "6", "8"], correct: 2 },
        { q: "Vad är 2³ + 3²?", answers: ["15", "17", "19", "13"], correct: 1 },
        { q: "Vilket tal är ett primtal?", answers: ["9", "15", "17", "21"], correct: 2 },
        { q: "Vad är 1/4 + 1/2?", answers: ["2/6", "3/4", "2/4", "1/3"], correct: 1 },
        { q: "Omkrets av kvadrat med sidan 5?", answers: ["10", "15", "20", "25"], correct: 2 },
        { q: "Vad är 3/5 av 100?", answers: ["30", "50", "60", "45"], correct: 2 },
        { q: "Nästa primtal efter 13?", answers: ["14", "15", "16", "17"], correct: 3 },
        { q: "Vad är 20% av 150?", answers: ["20", "25", "30", "35"], correct: 2 },
        { q: "Vad är 3² × 2?", answers: ["12", "16", "18", "24"], correct: 2 },
        { q: "Lös x + 5 = 12. Vad är x?", answers: ["5", "6", "7", "8"], correct: 2 },
        { q: "Vad är medianen av 2, 7 och 9?", answers: ["2", "7", "8", "9"], correct: 1 },
        { q: "Vad är 4(3 + 2)?", answers: ["14", "18", "20", "24"], correct: 2 },
        { q: "Vad är sannolikheten att slå en sexa med en tärning?", answers: ["1/2", "1/3", "1/6", "1/8"], correct: 2 },
    ],
    svenska: [
        { q: "Vilket ord är ett substantiv?", answers: ["Spring", "Snabb", "Hund", "Röd"], correct: 2 },
        { q: "Synonym till 'glad'?", answers: ["Ledsen", "Trött", "Lycklig", "Arg"], correct: 2 },
        { q: "Vilket är ett adjektiv?", answers: ["Hoppa", "Bord", "Vacker", "Snabbt"], correct: 2 },
        { q: "Vad heter satsens kärna?", answers: ["Subjekt", "Predikat", "Objekt", "Adverbial"], correct: 1 },
        { q: "Vilket ord stavas rätt?", answers: ["Examen", "Exxamen", "Eksamen", "Egzamen"], correct: 0 },
        { q: "Antonym till 'stor'?", answers: ["Bred", "Lång", "Liten", "Hög"], correct: 2 },
        { q: "Vilket är ett verb?", answers: ["Röd", "Snabbt", "Springer", "Hund"], correct: 2 },
        { q: "Vad är en metafor?", answers: ["En rimrad dikt", "En bildlig jämförelse", "Ett nyord", "En mening"], correct: 1 },
        { q: "Vad är allitteration?", answers: ["Upprepning av samma begynnelseljud", "Ett motsatsord", "Ett skiljetecken", "En källa"], correct: 0 },
        { q: "Vad är ett tema i en text?", answers: ["Textens övergripande ämne", "Antalet sidor", "Författarens namn", "Bokens pris"], correct: 0 },
        { q: "Vad är källkritik?", answers: ["Att granska om information är trovärdig", "Att skriva snabbt", "Att rimma", "Att läsa högt"], correct: 0 },
        { q: "Vilket ord är ett pronomen?", answers: ["Vi", "Bord", "Vacker", "Hoppa"], correct: 0 },
        { q: "Vad är en tes?", answers: ["En åsikt man argumenterar för", "En diktform", "Ett verb", "En rubrikstorlek"], correct: 0 },
        { q: "Vad betyder kronologisk ordning?", answers: ["Tidsordning", "Storleksordning", "Bokstavsordning", "Slumpordning"], correct: 0 },
        { q: "Vad är ett retoriskt knep?", answers: ["Ett sätt att övertyga", "En stavningsregel", "Ett substantiv", "En källa"], correct: 0 },
        { q: "Vad är objekt i en sats?", answers: ["Den som påverkas av handlingen", "Satsens handling", "En rubrik", "Ett rim"], correct: 0 },
    ],
    engelska: [
        { q: "What is 'äpple' in English?", answers: ["Orange", "Apple", "Pear", "Banana"], correct: 1 },
        { q: "What does 'beautiful' mean?", answers: ["Ful", "Konstig", "Vacker", "Stor"], correct: 2 },
        { q: "Past tense of 'go'?", answers: ["Goed", "Gone", "Went", "Goes"], correct: 2 },
        { q: "What is 'hund' in English?", answers: ["Cat", "Dog", "Bird", "Horse"], correct: 1 },
        { q: "Which word means 'snabb'?", answers: ["Slow", "Fast", "Heavy", "Tall"], correct: 1 },
        { q: "What does 'library' mean?", answers: ["Bokhandel", "Skola", "Bibliotek", "Museum"], correct: 2 },
        { q: "How do you say 'tack'?", answers: ["Please", "Sorry", "Hello", "Thank you"], correct: 3 },
        { q: "Plural of 'child'?", answers: ["Childs", "Childes", "Children", "Childrens"], correct: 2 },
        { q: "What is the past tense of 'write'?", answers: ["Wrote", "Written", "Writed", "Writes"], correct: 0 },
        { q: "What does 'actually' usually mean?", answers: ["Faktiskt", "Aktuellt", "Alltid", "Aldrig"], correct: 0 },
        { q: "Which sentence is grammatically correct?", answers: ["They are studying", "They is studying", "They am studying", "They be studying"], correct: 0 },
        { q: "What is a synonym for 'difficult'?", answers: ["Hard", "Easy", "Tiny", "Quiet"], correct: 0 },
        { q: "What does 'opinion' mean?", answers: ["Åsikt", "Fakta", "Fråga", "Källa"], correct: 0 },
        { q: "Plural of 'analysis'?", answers: ["Analyses", "Analysises", "Analysises", "Analysi"], correct: 0 },
        { q: "What does 'although' mean?", answers: ["Fastän", "Därför", "Alltid", "Snart"], correct: 0 },
        { q: "Which word is an adjective?", answers: ["Careful", "Run", "Table", "Yesterday"], correct: 0 },
    ],
    no: [
        { q: "Grundämne med symbolen O?", answers: ["Guld", "Ozon", "Syre", "Osmium"], correct: 2 },
        { q: "Hur många ben har ett insekt?", answers: ["4", "6", "8", "10"], correct: 1 },
        { q: "Jordens innersta lager?", answers: ["Manteln", "Skorpan", "Inre kärnan", "Yttre kärnan"], correct: 2 },
        { q: "Vilket organ pumpar blodet?", answers: ["Lungan", "Hjärnan", "Njuren", "Hjärtat"], correct: 3 },
        { q: "Vad producerar fotosyntesen?", answers: ["CO₂", "Vatten", "Socker och O₂", "Kväve"], correct: 2 },
        { q: "Minsta delen av ett grundämne?", answers: ["Molekyl", "Atom", "Neutron", "Elektron"], correct: 1 },
        { q: "Vilken planet är närmast solen?", answers: ["Venus", "Mars", "Merkurius", "Jorden"], correct: 2 },
        { q: "Vad är DNA?", answers: ["Ett protein", "Ärftlig information", "En cell", "Ett virus"], correct: 1 },
        { q: "Vad kallas ämnen som startar en kemisk reaktion?", answers: ["Reaktanter", "Produkter", "Enzymer", "Isotoper"], correct: 0 },
        { q: "Vad är en cellkärnas uppgift?", answers: ["Innehålla och styra med DNA", "Pumpa blod", "Bryta ner ljus", "Lagra syre"], correct: 0 },
        { q: "Vad mäts elektrisk ström i?", answers: ["Ampere", "Volt", "Watt", "Ohm"], correct: 0 },
        { q: "Vad innebär evolution?", answers: ["Att arter förändras över tid", "Att planeter snurrar", "Att vatten fryser", "Att ljus böjs"], correct: 0 },
        { q: "Vad är pH ett mått på?", answers: ["Hur surt eller basiskt något är", "Hur varmt något är", "Hur tungt något är", "Hur snabbt något rör sig"], correct: 0 },
        { q: "Vad kallas energi som rörelse har?", answers: ["Rörelseenergi", "Lägesenergi", "Kemisk energi", "Kärnenergi"], correct: 0 },
        { q: "Vad är en hypotes?", answers: ["En testbar förklaring", "Ett färdigt facit", "En mätsticka", "En celltyp"], correct: 0 },
        { q: "Vad kallas kraften som bromsar rörelse mellan ytor?", answers: ["Friktion", "Gravitation", "Spänning", "Densitet"], correct: 0 },
    ],
    so: [
        { q: "Vilket land har flest invånare?", answers: ["Indien", "USA", "Ryssland", "Kina"], correct: 3 },
        { q: "Vad heter Sveriges riksdag?", answers: ["Stortinget", "Riksdagen", "Folketinget", "Altinget"], correct: 1 },
        { q: "Vilket hav är störst?", answers: ["Atlanten", "Indiska oceanen", "Arktiska oceanen", "Stilla havet"], correct: 3 },
        { q: "Hur många kommuner i Sverige?", answers: ["190", "290", "390", "490"], correct: 1 },
        { q: "Vad kallas folk som flyr till annat land?", answers: ["Turister", "Flyktingar", "Invandrare", "Diplomater"], correct: 1 },
        { q: "Vilket land är störst till ytan?", answers: ["Kanada", "Kina", "USA", "Ryssland"], correct: 3 },
        { q: "Vad är urbanisering?", answers: ["Att fler människor flyttar till städer", "Att hav blir större", "Att berg bildas", "Att språk försvinner"], correct: 0 },
        { q: "Vad är BNP?", answers: ["Mått på ett lands ekonomi", "En typ av karta", "Ett väderfenomen", "En valuta"], correct: 0 },
        { q: "Vad är en grundlag?", answers: ["En extra viktig lag", "En karta", "Ett avtal om handel", "En skatt"], correct: 0 },
        { q: "Vad betyder migration?", answers: ["Att människor flyttar", "Att rösta", "Att odla", "Att mäta väder"], correct: 0 },
        { q: "Vad är inflation?", answers: ["När priser stiger över tid", "När solen går upp", "När befolkningen minskar", "När berg vittrar"], correct: 0 },
        { q: "Vad är en naturresurs?", answers: ["Något från naturen som människor använder", "En stad", "En lag", "En budget"], correct: 0 },
        { q: "Vad är parlamentarism?", answers: ["Regeringen måste ha stöd i parlamentet", "Alla röstar varje dag", "Domstolar skriver lagar", "Kommuner styr världen"], correct: 0 },
        { q: "Vad betyder hållbar utveckling?", answers: ["Att möta behov utan att förstöra för framtiden", "Att bygga högst", "Att alltid öka priser", "Att bara använda olja"], correct: 0 },
        { q: "Vad är en marknadsekonomi?", answers: ["Utbud och efterfrågan styr mycket", "Staten styr alla priser", "Ingen får sälja varor", "Alla varor är gratis"], correct: 0 },
        { q: "Vad är erosion?", answers: ["När mark nöts ner av vatten, vind eller is", "När priser stiger", "När människor röstar", "När städer växer"], correct: 0 },
    ],
    historia: [
        { q: "När började första världskriget?", answers: ["1904", "1914", "1918", "1939"], correct: 1 },
        { q: "Vilket år föll Berlinmuren?", answers: ["1985", "1987", "1989", "1991"], correct: 2 },
        { q: "Atenska demokratins grundare?", answers: ["Sokrates", "Perikles", "Solon", "Platon"], correct: 2 },
        { q: "När avskaffades slaveriet i USA?", answers: ["1848", "1863", "1876", "1901"], correct: 1 },
        { q: "Apollo 11 landade på månen?", answers: ["1965", "1967", "1969", "1971"], correct: 2 },
        { q: "Frankrikes kejsare på 1800-talet?", answers: ["Ludvig XIV", "Robespierre", "Napoleon", "Richelieu"], correct: 2 },
        { q: "Andra världskriget startade?", answers: ["1935", "1937", "1939", "1941"], correct: 2 },
        { q: "Vad var Kolosseum?", answers: ["Ett tempel", "En amfiteater", "Ett palats", "En marknadsplats"], correct: 1 },
        { q: "Vad var renässansen?", answers: ["En period av nya idéer inom konst och vetenskap", "Ett världskrig", "En valuta", "En svensk lag"], correct: 0 },
        { q: "Vad var franska revolutionen?", answers: ["En politisk omvälvning i Frankrike", "En upptäcktsresa", "En industri", "En fredspakt i Norden"], correct: 0 },
        { q: "Vad betyder industrialisering?", answers: ["Övergång till maskiner och fabriker", "Att odla mer skog", "Att skriva lagar", "Att byta språk"], correct: 0 },
        { q: "Vad var kalla kriget?", answers: ["En konflikt mellan öst och väst utan direkt storkrig", "Ett krig på medeltiden", "En svensk kungatid", "En handelsresa"], correct: 0 },
        { q: "Vad är historiebruk?", answers: ["Hur historia används i olika sammanhang", "Hur man bygger hus", "Hur man mäter tid", "Hur man skriver alfabetet"], correct: 0 },
        { q: "Vad var upplysningen?", answers: ["En idéströmning om förnuft och kunskap", "En vikingaresa", "Ett väderfenomen", "En medeltida skatt"], correct: 0 },
        { q: "Vad var imperialism?", answers: ["När stater tog kontroll över andra områden", "När böcker trycktes", "När is smälter", "När val hålls"], correct: 0 },
        { q: "Vad betyder kontinuitet i historia?", answers: ["Sådant som fortsätter över tid", "En snabb revolution", "Ett enskilt datum", "En karta över städer"], correct: 0 },
    ],
};

export function getQuestionPool(subject, grade) {
    const gradeNumber = Number(grade);
    if (gradeNumber <= 3) return lowerGradeQuestions[subject] ?? upperGradeQuestions[subject];
    if (gradeNumber <= 6) return middleGradeQuestions[subject] ?? upperGradeQuestions[subject];
    return upperGradeQuestions[subject];
}
